### PR TITLE
Do not return versions of providers that do not have platforms

### LINKED ISSUE #55: Bug: Registry is listing irrelevant provider versions, which causes opentf to fail
Using this registry, we cannot use `opentf` to install the `hashicorp/oci` providers. When attempting to list the versions, you'd get the following error:

`Could not retrieve the list of available versions for provider oracle/oci: could not query provider registry for registry.opentf.org/oracle/oci: registry response includes invalid version string ".374.0": invalid specification; required format is three positive integers separated by periods`

Reason being - we return broken versions, including versions that have no assets (`platforms: null`)

We should only return versions that have any assets, and drop the ones that don't

### PR DESCRIPTION
**Pull request by Yantrio**
Fixes #55

### CODE REVIEW

File: lambda/internal/providers/versions.go [hunk 1]
```diff
@@ -54,6 +54,13 @@ func GetVersions(ctx context.Context, ghClient *githubv4.Client, namespace strin
 					return
 				}
 
+				// if there are no platforms, we can't do anything with this release
+				// so, we should just skip
+
+				if len(platforms) == 0 {
+					return
```
Comment (eranelbaz) [inline lambda/internal/providers/versions.go:61]: maybe let's log it?

**Review by RLRabinowitz — APPROVED** [review]

**Review by eranelbaz — APPROVED** [review]

**Review by cube2222 — APPROVED** [review]

**Review by tomasmik — APPROVED** [review]

File: lambda/internal/providers/versions.go (hunk 1 above)
Comment (Yantrio) [reply lambda/internal/providers/versions.go:61]: I don't see the use in logging this here.
