### PR TITLE
Don't throw 502s if the resource isn't found

### LINKED ISSUE #102: Calling registry's REST API returns HTTP 502
The expectation is to get 404 [according to James](https://opentofucommunity.slack.com/archives/C05UH44L449/p1695824342861689?thread_ts=1695824208.634509&cid=C05UH44L449).
Here's the output:

```bash
curl -v https://registry.opentofu.org/v1/providers/hashicorp/aws/5.18.1/download/darwin/x86_64

*   Trying 18.66.147.94:443...
* Connected to registry.opentofu.org (18.66.147.94) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=registry.opentofu.org
*  start date: Sep 20 00:00:00 2023 GMT
*  expire date: Oct 18 23:59:59 2024 GMT
*  subjectAltName: host "registry.opentofu.org" matched cert's "registry.opentofu.org"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M02
*  SSL certificate verify ok.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: registry.opentofu.org]
* h2 [:path: /v1/providers/hashicorp/aws/5.18.1/download/darwin/x86_64]
* h2 [user-agent: curl/8.1.2]
* h2 [accept: */*]
* Using Stream ID: 1 (easy handle 0x7fd2e500fc00)
> GET /v1/providers/hashicorp/aws/5.18.1/download/darwin/x86_64 HTTP/2
> Host: registry.opentofu.org
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/2 502 
< content-type: application/json
< content-length: 36
< date: Wed, 27 Sep 2023 14:14:46 GMT
< x-amzn-requestid: 6ffd0957-0e9c-47c6-94c7-f36ca9aea18a
< x-amzn-errortype: InternalServerErrorException
< x-amz-apigw-id: L63QSFoBDoEFwvA=
< x-amzn-trace-id: Root=1-651438ce-041cc0b63bba5d3636f6d856
< x-cache: Error from cloudfront
< via: 1.1 b1c64361268fcbad3c03abbe37eb5cfa.cloudfront.net (CloudFront)
< x-amz-cf-pop: FRA60-P4
< x-amz-cf-id: luPoqcd-mJAF1HwXHOLYq-zoTHWmMxa2-OqaWnbt6DErB9DWCoh6BA==
< 
* Connection #0 to host registry.opentofu.org left intact
{"message": "Internal server error"}
```

### PR DESCRIPTION
**Pull request by Yantrio**
Fixes #102 

As an expansion of #104 I've raised this PR

(The old PR needed a lot of rebasing doing, and the author was unable to work on this until wednesday)

I've taken the same concept but instead of using http codes I've just defined some codes as constants that we can use.

### CODE REVIEW

File: src/internal/providers/errors.go [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+
+type FetchErrorCode int
+
+const (
+	ErrCodeReleaseNotFound       FetchErrorCode = 1
+	ErrCodeAssetNotFound         FetchErrorCode = 2
+	ErrCodeSHASumsNotFound       FetchErrorCode = 3
+	ErrCodeManifestNotFound      FetchErrorCode = 4
+	ErrCodeCouldNotGetPublicKeys FetchErrorCode = 5
+)
```
Comment (eranelbaz) [inline src/internal/providers/errors.go:13]: Why do we need those codes?
to make 404 more verbose?

File: src/internal/providers/errors.go [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+	Code    FetchErrorCode
+}
+
+func (p *FetchError) Error() string {
+	return fmt.Sprintf("%d, %s", p.Code, p.Message)
+}
+
+func (p *FetchError) Unwrap() error {
+	return p.Inner
+}
```
Comment (eranelbaz) [inline src/internal/providers/errors.go:27]: Why do we need this?

**Review by eranelbaz — COMMENTED** [review]
Just questions

File: src/internal/providers/errors.go [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+
+func newFetchError(message string, code FetchErrorCode, err error) error {
+	return &FetchError{
+		Message: message,
+		Code:    code,
+		Inner:   err,
+	}
+}
```
Comment (eranelbaz) [inline src/internal/providers/errors.go:35]: Why `new`? isn't is `get`? or `create`?

File: src/lambda/api/providerDownload.go [hunk 4]
```diff
@@ -83,6 +84,16 @@ func downloadProviderVersion(config config.Config) LambdaFunc {
 func fetchVersionFromGithub(ctx context.Context, config config.Config, effectiveNamespace string, repoName string, params DownloadHandlerPathParams) (events.APIGatewayProxyResponse, error) {
 	versionDownloadResponse, err := providers.GetVersion(ctx, config.RawGithubv4Client, effectiveNamespace, repoName, params.Version, params.OS, params.Architecture)
 	if err != nil {
+		var fetchErr *providers.FetchError
+		// if it's a providers.FetchError
+		if errors.As(err, &fetchErr) {
+			if fetchErr.Code == providers.ErrCodeReleaseNotFound {
```
Comment (RLRabinowitz) [inline src/lambda/api/providerDownload.go]: Would we want the same behaviour for "Asset not found"? And maybe for other types of error as well?
What would be the result in a failed `tofu init`?

File: src/internal/providers/errors.go [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+import "fmt"
+
+type FetchErrorCode int
+
+const (
+	ErrCodeReleaseNotFound       FetchErrorCode = 1
+	ErrCodeAssetNotFound         FetchErrorCode = 2
+	ErrCodeSHASumsNotFound       FetchErrorCode = 3
+	ErrCodeManifestNotFound      FetchErrorCode = 4
+	ErrCodeCouldNotGetPublicKeys FetchErrorCode = 5
```
Comment (RLRabinowitz) [inline src/internal/providers/errors.go:12]: nit: I imagine it would look clearer if those were actual Errors, and not error codes of the `FetchError`.
Would be nicer than having to `if errors.As(err, &fetchErr) { if fetchErr.Code = providers.ErrCodeReleaseNotFound...` when checking the error type

File: src/internal/providers/errors.go (hunk 2 above)
Comment (Yantrio) [reply src/internal/providers/errors.go:27]: because it's a wrapped error

File: src/internal/providers/errors.go (hunk 3 above)
Comment (Yantrio) [reply src/internal/providers/errors.go:35]: because its a constructor

File: src/internal/providers/errors.go (hunk 1 above)
Comment (Yantrio) [reply src/internal/providers/errors.go:13]: Because only ErrCodeReleaseNotFound should result in a 404 in the http handler layer. 
But, also, the internal providers package shouldn't have knowledge of how it's consumed.

File: src/lambda/api/providerDownload.go (hunk 4 above)
Comment (Yantrio) [reply src/lambda/api/providerDownload.go]: As this is fetching from github (and in reality this should rarely happen), I feel like we should just handle the ReleaseNotFound. However, its also valid that we handle if the os/architecture is not found (this will bubble up as `ErrCodeAssetNotFound`)

I think you're right here, we should 404 on the following:

- ReleaseNotFound
- AssetNotFound

and error on the rest. I'll update this code now.

File: src/internal/providers/errors.go (hunk 5 above)
Comment (Yantrio) [reply src/internal/providers/errors.go:12]: Sentinel errors here make error checking later on much harder.

Also using wrapped errors this way with codes is an idiomatic way of error handling in go.

File: src/internal/providers/errors.go (hunk 2 above)
Comment (cube2222) [reply src/internal/providers/errors.go:27]: @eranelbaz see https://pkg.go.dev/errors for more details.

**Review by cube2222 — APPROVED** [review]
Explicit types for each (instead of error codes) would be a bit more elegant imo and easy to match against.

But then again, that's a lot of boilerplate.

Anyway, for the alpha registry it's LGTM.

File: src/lambda/api/providerDownload.go [hunk 6]
```diff
@@ -83,6 +84,16 @@ func downloadProviderVersion(config config.Config) LambdaFunc {
 func fetchVersionFromGithub(ctx context.Context, config config.Config, effectiveNamespace string, repoName string, params DownloadHandlerPathParams) (events.APIGatewayProxyResponse, error) {
 	versionDownloadResponse, err := providers.GetVersion(ctx, config.RawGithubv4Client, effectiveNamespace, repoName, params.Version, params.OS, params.Architecture)
 	if err != nil {
+		var fetchErr *providers.FetchError
+		// if it's a providers.FetchError
+		if errors.As(err, &fetchErr) {
+			if fetchErr.Code == providers.ErrCodeReleaseNotFound || fetchErr.Code == providers.ErrCodeAssetNotFound {
+				slog.Info("Release not found in repo")
+				return NotFoundResponse, nil
+			}
```
Comment (eranelbaz) [inline src/lambda/api/providerDownload.go]: Sounds like there is a different `ErrCodeReleaseNotFound` and `CodeAssetNotFound`?
Those two are indeed 404 but different logs IMO

**Review by tomasmik — APPROVED** [review]

File: src/lambda/api/providerDownload.go (hunk 6 above)
Comment (Yantrio) [reply src/lambda/api/providerDownload.go]: I've seperated the logging here for the 2
